```{r}
library(tidyverse)
library(scales)
library(RColorBrewer)
library(arrow)
library(ggtext)

caption <- "Max Woolf — minimaxir.com"

sessionInfo()
```

```{r}
theme_set(theme_minimal(base_size = 8, base_family = "Overpass") +
  theme(
    plot.title = element_text(size = 8, face = "bold"),
    plot.subtitle = element_text(color = "#666666", size = 6),
    axis.title.x = element_text(size = 6),
    axis.title.y = element_text(size = 6),
    plot.caption = element_text(size = 5, color = "#969696"),
    plot.background = element_rect(fill = "#FFFFFF", color = "#FFFFFF"),
    legend.title = element_text(size = 8),
    # legend.key.width = unit(0.25, unit = "cm"),
    # panel.grid.minor = element_blank()
  ))
```


```{r}
df <- read_parquet("/Users/maxwoolf/Downloads/imdb_embeddings_2d.parquet")

df |> head()
```

## 2D UMAP Projection

```{r}
plot <- ggplot(df, aes(x = x_2d, y = y_2d, color = averageRating)) +
  geom_point(size = 0.4, stroke = 0.0, alpha = 0.8) +
  # scale_x_continuous(limits = c(-4.7, 4.7)) +
  # scale_y_continuous(limits = c(-5.2, 4.7)) +
  scale_color_distiller(palette = "PRGn", breaks = seq(1, 10, 1), direction = 1) +
  labs(
    title = sprintf("2D UMAP Projection of %s IMDb Movie Embeddings", df |> nrow() |> comma()),
    subtitle = "All movies with atleast 30 user votes until 2025-05-10. Colors represent average IMDb user rating.",
    caption = caption
  ) +
  theme(
    legend.position = "top",
    legend.title = element_blank(),
    legend.text = element_text(size = 5, margin = margin(c(0.05, 0.0, 0.0, 0.0), unit = "cm")),
    legend.key.width = unit(1.5, unit = "cm"),
    legend.key.height = unit(0.25, unit = "cm"),
    legend.margin = margin(c(0.0, 0.5, -0.2, 0.4), unit = "cm"),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
  )

ggsave("imdb_umap_rating.png", plot, width = 4, height = 4)
```

Investigate that weird top cluster.

```{r}
all_data <- read_parquet("/Users/maxwoolf/Downloads/movie_data_plus_embeds_all.parquet", col_select = c("tconst", "json", "averageRating", "numVotes", "startYear"))

df |>
  filter(x_2d <= -3, y_2d >= 10) |>
  left_join(all_data) |>
  write_csv("/Users/maxwoolf/Downloads/top_cluster.csv")
```

Appears to be 2008 movies only. Check other clusters.

```{r}
df |>
  filter(x_2d <= -4.5, y_2d >= -1, y_2d <= 1) |>
  left_join(all_data) |>
  write_csv("/Users/maxwoolf/Downloads/cluster_1.csv")
```

All 2003 movies apparently.

```{r}
df |>
  filter(x_2d >= 1, x_2d <= 2.5, y_2d >= -7, y_2d <= -4) |>
  left_join(all_data) |>
  write_csv("/Users/maxwoolf/Downloads/cluster_2.csv")
```

All 2024 movies apparently.

```{r}
plot <- ggplot(df |> left_join(all_data) |> filter(startYear >= 1996), aes(x = x_2d, y = y_2d, color = factor(startYear))) +
  geom_point(size = 0.3, stroke = 0.0, alpha = 0.5) +
  scale_color_hue(guide = "none") +
  labs(
    title = "2D UMAP Projection of IMDb Movie Embeddings, Faceted by Release Year",
    subtitle = "All movies with atleast 30 user votes until 2025-05-10. Colors represent release year.",
    caption = caption
  ) +
  theme(
    # legend.position = "top",
    # legend.title = element_blank(),
    # legend.text = element_text(size = 5, margin = margin(c(0.05, 0.0, 0.0, 0.0), unit = "cm")),
    # legend.key.width = unit(1.5, unit = "cm"),
    # legend.key.height = unit(0.25, unit = "cm"),
    # legend.margin = margin(c(0.0, 0.5, -0.2, 0.4), unit = "cm"),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
  ) +
  facet_wrap(~startYear)

ggsave("imdb_umap_rating_year.png", plot, width = 4, height = 4)
```

## Actor Distribution by Unique Movies

```{r}
df_actors <- read_parquet("/Users/maxwoolf/Downloads/actor_agg.parquet")

df_actors |> head()
```

```{r}
plot <- ggplot(df_actors |> head(100000) |> mutate(row_n = row_number()), aes(x = row_n, y = movie_count)) +
  geom_bar(stat = "identity", color = "#2f3640") +
  labs(
    title = "# of Movies An Actor Has Acted In, Sorted From Most Prolific to Least Prolific",
    subtitle = "For all IMDb movies with atleast 30 user votes until 2025-05-10.",
    x = "*n*th Unique Actor",
    y = "# of Total Movies Actor Has Acted In",
    caption = caption
  ) +
  theme(
    axis.title.x = element_markdown()
  )

ggsave("actor_cum_dist.png", plot, width = 5, height = 2.5)
```

## Model Training Loops

```{r}
df_train_mlp <- read_parquet("mlp_train_logs.parquet")

df_train_mlp |> head()
```

```{r}
df_train_mlp_long <- df_train_mlp |>
  select(epoch, train_loss = loss, test_loss = eval_loss) |>
  pivot_longer(!epoch, names_to = "loss_type", values_to = "loss")

df_train_mlp_long |> head()
```

```{r}
df_train_mlp_long |>
  filter(loss_type == "test_loss") |>
  filter(loss == min(loss))
```

```{r}
df_train_llm <- read_parquet("llm_scratch_train_logs.parquet")

df_train_llm |> head()
```

```{r}
df_train_llm_long <- df_train_llm |>
  select(epoch, train_loss = loss, test_loss = eval_loss) |>
  pivot_longer(!epoch, names_to = "loss_type", values_to = "loss")

df_train_llm_long |> head()
```

```{r}
min_test_loss <- df_train_mlp_long |>
  filter(loss_type == "test_loss") |>
  filter(loss == min(loss))

plot <- ggplot(df_train_mlp_long, aes(x = epoch, y = loss, color = loss_type, fill = loss_type)) +
  geom_line() +
  geom_point(data = min_test_loss, shape = 21, color = "white") +
  geom_label(data = min_test_loss, aes(label = loss |> round(3), y = loss - 0.025), family = "Overpass", color = "white", show.legend = FALSE, size = 2) +
  scale_x_continuous(limits = c(0, 600), breaks = seq(0, 600, 100)) +
  scale_y_continuous(limits = c(0.8, 1.2), breaks = seq(0.8, 1.2, 0.1)) +
  labs(
    title = "Training Loss for MLP to Predict IMDb Average Movie Ratings",
    subtitle = "For all IMDb movies with atleast 30 user votes until 2025-05-10.",
    x = "Epoch",
    y = "MSE Loss (Lower is Better)",
    caption = caption
  ) +
  theme(
    legend.title = element_blank()
  )

ggsave("training_mlp.png", plot, width = 4, height = 2.5)
```

```{r}
min_test_loss <- df_train_llm_long |>
  filter(loss_type == "test_loss") |>
  filter(loss == min(loss))

plot <- ggplot(df_train_llm_long, aes(x = epoch, y = loss, color = loss_type, fill = loss_type)) +
  geom_line() +
  geom_point(data = min_test_loss, shape = 21, color = "white") +
  geom_label(data = min_test_loss, aes(label = loss |> round(3), y = loss - 0.025), family = "Overpass", color = "white", show.legend = FALSE, size = 2) +
  scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, 1)) +
  scale_y_continuous(limits = c(0.8, 1.2), breaks = seq(0.8, 1.2, 0.1)) +
  labs(
    title = "Training Loss for LLM to Predict IMDb Average Movie Ratings",
    subtitle = "For all IMDb movies with atleast 30 user votes until 2025-05-10.",
    x = "Epoch",
    y = "MSE Loss (Lower is Better)",
    caption = caption
  ) +
  theme(
    legend.title = element_blank(),
    panel.grid.minor.x = element_blank()
  )

ggsave("training_llm.png", plot, width = 4, height = 2.5)
```

## Comparing Models

```{r}
df_models <- read_csv("imdb_grid_search.csv")

df_models |> head()
```

```{r}
df_models_f <- df_models |>
  group_by(model) |>
  arrange(test_mse) |>
  filter(row_number() == 1) |>
  ungroup() |>
  mutate(model_type = "Traditional\nModel", model = factor(model, levels = model))

df_models_f
```

```{r}
colors <- c("Traditional\nModel" = "#27ae60", "Neural\nNetwork" = "#2980b9")

plot <- ggplot(df_models_f, aes(x = test_mse, y = model, fill = model_type, color = model_type)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = test_mse |> round(3)), family = "Overpass", fontface = "bold", size = 2.5, nudge_x = 0.15) +
  scale_x_continuous(limits = c(0, 1.5)) +
  scale_y_discrete(limits = rev) +
  scale_fill_manual(values = colors) +
  scale_color_manual(values = colors) +
  labs(
    title = "Model Performance For Predicting\nIMDb Average Movie Ratings w/ LLM Embeddings",
    # subtitle = "For all IMDb movies with atleast 30 user votes until 2025-05-10.",
    x = "Test MSE Loss of Best Model (Lower is Better)",
    # fill = "Implementation Correctness",
    caption = caption
  ) +
  theme(
    # legend.position = "top",
    legend.title = element_blank(),
    # legend.text = element_text(size = 5, margin = margin(c(0.0, 0.0, 0.0, 0.1), unit = "cm")),
    # legend.key.width = unit(0.50, unit = "cm"),
    # legend.key.height = unit(0.25, unit = "cm"),
    # legend.margin = margin(c(0.0, 0.5, -0.2, 0.4), unit = "cm"),
    axis.text.x = element_text(size = 6, angle = 90, vjust = 0.5),
    axis.text.y = element_text(size = 6),
    # axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    # axis.ticks = element_line(linewidth = 0.5, color = "#969696"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.x = element_blank(),
    plot.title = element_text(hjust = 0.5),
    # plot.subtitle = element_text(hjust = 0.5),
    # axis.ticks.length.x = unit(., "cm"),
    # axis.ticks.length.y = unit(.25, "cm"),
  )

ggsave("model_comparison_base.png", plot, width = 4, height = 2.5)
```
